version: '3.9'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8426:80"
    volumes:
      - ../../../:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1

  db:
    image: mysql:lts
    ports:
      - "127.0.0.1:8427:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../../../../db-data:/var/lib/mysql

volumes:
  volumes:
  db_data:
